

GET http://localhost:3002/todos

###

POST http://localhost:3002/todo/new 
Content-Type: application/json

{
"text": " i want this to delete"
}

###

DELETE http://localhost:3002/todo/delete/6414eb9967681490e932cbd6


### should cross off
GET http://localhost:3002/todo/complete/6414eb8567681490e932cbd0


### should replace 

PUT http://localhost:3002/todo/update/6414eb8567681490e932cbd0 
Content-Type: application/json

{
"text": "how about this"
}