

GET http://localhost:3002/todos

###

POST http://localhost:3002/todo/new 
Content-Type: application/json

{
"text": ""
}

###

DELETE http://localhost:3002/todo/delete/6414eb9967681490e932cbd6


### should cross off
GET http://localhost:3002/todo/complete/6414eb8567681490e932cbd0



PUT http://localhost:3002/todo/update/64135f5822bd2101dd477b07 
Content-Type: application/json

{
"text": ""
}